global:
  scrape_interval: 15s # Prometheus akan mengambil data setiap 15 detik

scrape_configs:
  - job_name: 'tasmota_esp32'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.25.25.71:80'] # IP ESP32 Anda di jaringan ap0 host

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['172.30.30.40:9091'] # IP Pushgateway yang kita set di docker-compose
  
  # Tambahkan Job Node Exporter di bawah ini
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.30.30.1:9100'] # Menggunakan IP Gateway Docker Host

  - job_name: 'blackbox_ping'
    metrics_path: /probe
    params:
      module: [icmp_check]
    static_configs:
      - targets:
          - 172.25.25.71      # IP ESP32 Anda
          - 8.8.8.8           # DNS Google (untuk cek internet)
          - 172.50.50.1       # redmi note 0
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # Karena Blackbox pakai mode host, Prometheus memanggilnya via Gateway
        replacement: 172.30.30.1:9115

  - job_name: 'redmi_note_9'
    static_configs:
      - targets: ['172.50.50.1:9100']
        labels:  # <--- Pastikan ini menjorok ke dalam (di bawah targets)
          device: 'merlin'
          type: 'mobile'