{
 "title": "thinkpad",
 "description": "thinkpad,tasmota",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Thinkpad CPU usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=\"172.30.30.1:9100\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad Fan",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_thinkpad_hwmon\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MerlinCpu Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{instance=\"172.50.50.1:9100\", zone=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 8.8.8.8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"8.8.8.8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin CPU usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=\"172.50.50.1:9100\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status eps32",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"172.25.25.71\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"172.30.30.1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad Ram Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"172.30.30.1:9100\"} - node_memory_MemAvailable_bytes{instance=\"172.30.30.1:9100\"}) / node_memory_MemTotal_bytes{instance=\"172.30.30.1:9100\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad RX TX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"wlp4s0\"} + node_network_transmit_bytes_total{device=\"wlp4s0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlincharger",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_online{instance=\"172.50.50.1:9100\", power_supply=\"ac\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad Cpu Temp",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(node_hwmon_temp_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Merlin Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"172.50.50.1:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_power_supply_energy_watthour) / sum(node_power_supply_energy_full)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thinkpad charger",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_power_supply_online{power_supply=\"AC\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"172.50.50.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merlin Ram Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"172.50.50.1:9100\"} - node_memory_MemAvailable_bytes{instance=\"172.50.50.1:9100\"}) / node_memory_MemTotal_bytes{instance=\"172.50.50.1:9100\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}