[mikrotik-grafana]
    enabled = True
    hostname = 10.10.10.10
    username = mikrotik-grafana
    password = mikrotik-grafana
[default]

# The section below contains the latest default parameters introduced by MKTXP
# For organizational purposes, you can move these parameters to the [default] section
[new_default_parameters]
    routing_stats = False
    dhcp_lease = True
    certificate = False
    firewall = True
    connection_stats = False
    eoip = False
    health = True
    kid_control_assigned = False
    container = False
    dhcp = True
    bfd = False
    wireless_clients = True
    connections = True
    enabled = False
    switch_port = False
    no_ssl_certificate = False
    w60g = False
    ipv6_route = False
    ssl_certificate_verify = False
    capsman = True
    pool = True
    wireless = True
    user = True
    gre = False
    monitor = True
    ssl_check_hostname = True
    public_ip = True
    plaintext_login = True
    check_for_updates = False
    netwatch = True
    ipsec = False
    capsman_clients = True
    ipip = False
    installed_packages = True
    bgp = False
    queue = True
    interface = True
    ipv6_pool = False
    dns = False
    route = True
    ipv6_firewall = False
    kid_control_dynamic = False
    module_only = False
    lte = False
    use_ssl = False
    poe = True
    neighbor = True
    ipv6_neighbor = False
    hostname = localhost
    username = user
    password = password
    credentials_file = ""
    ssl_ca_file = ""
    remote_dhcp_entry = None
    remote_capsman_entry = None
    address_list = None
    ipv6_address_list = None
    custom_labels = None
    interface_name_format = name
    port = 8728
