# Load modul UDP port 514
module(load="imudp")
input(type="imudp" port="514")

# 1. Buat Template Lokasi File Log per Kota
template(name="JakartaLog" type="string" string="/var/log/mikrotik/jakarta/%HOSTNAME%.log")
template(name="BandungLog" type="string" string="/var/log/mikrotik/bandung/%HOSTNAME%.log")
template(name="SurabayaLog" type="string" string="/var/log/mikrotik/surabaya/%HOSTNAME%.log")
template(name="AcehLog" type="string" string="/var/log/mikrotik/aceh/%HOSTNAME%.log")
template(name="DefaultLog" type="string" string="/var/log/mikrotik/others/%HOSTNAME%.log")

# 2. Filter Log Berdasarkan Kata Kunci Hostname/Identity
if ($hostname contains "jakarta") then {
    action(type="omfile" dynaFile="JakartaLog" dirCreateMode="0755")
} else if ($hostname contains "bandung") then {
    action(type="omfile" dynaFile="BandungLog" dirCreateMode="0755")
} else if ($hostname contains "surabaya") then {
    action(type="omfile" dynaFile="SurabayaLog" dirCreateMode="0755")
} else if ($hostname contains "aceh") then {
    action(type="omfile" dynaFile="AcehLog" dirCreateMode="0755")
} else {
    action(type="omfile" dynaFile="DefaultLog" dirCreateMode="0755")
}
