[jakarta_core]
core_jakarta ansible_host=10.90.90.2

[jakarta_routers]
jakarta_r1 ansible_host=10.90.90.3
jakarta_r2 ansible_host=10.90.90.4
jakarta_r3 ansible_host=10.90.90.5

[area_jakarta:children]
jakarta_core
jakarta_routers
