[local-isp]
    enabled = True
    hostname = 10.10.10.10
    username = local-isp
    password = local-isp
    port = 8728
    
    # Bagian metrik yang ingin diambil
    system_resource = True
    interface = True
    route = True
    dhcp_lease = True
    wireless = True
    firewall = True
    monitor = True
    pool = True                     # IPv4 Pool metrics         
    neighbor = True                 # IPv4 Reachable Neighbors
    address_list = True             # Firewall Address List metrics, a comma-separated list of names
    dns = True

[default]
    # Konfigurasi global untuk semua router
    plaintext_login = True
    socket_timeout = 5

# The section below contains the latest default parameters introduced by MKTXP
# For organizational purposes, you can move these parameters to the [default] section
[new_default_parameters]
    switch_port = False
    wireless = True
    bfd = False
    monitor = True
    routing_stats = False
    user = True
    kid_control_dynamic = False
    netwatch = True
    bgp = False
    queue = True
    neighbor = True
    ssl_certificate_verify = False
    certificate = False
    route = True
    poe = True
    public_ip = True
    ipv6_route = False
    enabled = False
    dhcp_lease = True
    use_ssl = False
    lte = False
    ssl_check_hostname = True
    container = False
    check_for_updates = False
    capsman = True
    gre = False
    ipip = False
    dns = False
    dhcp = True
    kid_control_assigned = False
    eoip = False
    connections = True
    module_only = False
    capsman_clients = True
    ipsec = False
    pool = True
    ipv6_pool = False
    ipv6_neighbor = False
    firewall = True
    no_ssl_certificate = False
    ipv6_firewall = False
    interface = True
    connection_stats = False
    w60g = False
    wireless_clients = True
    installed_packages = True
    health = True
    hostname = localhost
    username = user
    password = password
    credentials_file = ""
    ssl_ca_file = ""
    remote_dhcp_entry = None
    remote_capsman_entry = None
    address_list = None
    ipv6_address_list = None
    custom_labels = None
    interface_name_format = name
    port = 8728
