# Load module UDP
module(load="imudp")
input(type="imudp" port="10500")

# core-jakarta
if $fromhost-ip == '10.10.10.10' then /var/log/core-jakarta.log
& stop

# jakarta-r1
if $fromhost-ip == '172.10.10.2' then /var/log/jakarta-r1.log
& stop

# Sisanya buang ke stdout agar muncul di 'docker logs'
*.* /dev/stdout
