version: "3.8"

services:
  zerotier:
    image: zerotier/zerotier
    container_name: zerotier-router1
    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    volumes:
      - ./zerotier:/var/lib/zerotier-one

    networks:
      docker-zerotier:
        ipv4_address: 172.20.20.10

    command: zerotier-one

networks:
  docker-zerotier:
    external: true
